image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test
  - dockerbuild
  - sonar

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:12.14.1-alpine3.11
  script: npm i && npm run build

test:
  stage: test
  image: node:12.14.1-alpine3.11
  script:
    - npm run testgit

sonar:
  stage: sonar
  image:
    name: sonarsource/sonar-scanner-cli:4.2
    entrypoint: [""]
  script: sonar-scanner
